src/main/kotlin/com/codersgate/ticketraider/TicketRaiderApplication.kt
src/main/kotlin/com/codersgate/ticketraider/common/BaseEntity.kt
src/main/kotlin/com/codersgate/ticketraider/domain/category/controller/CategoryController.kt
src/main/kotlin/com/codersgate/ticketraider/domain/category/dto/CategoryResponse.kt
src/main/kotlin/com/codersgate/ticketraider/domain/category/dto/CreateCategoryRequest.kt
src/main/kotlin/com/codersgate/ticketraider/domain/category/dto/UpdateCategoryRequest.kt
src/main/kotlin/com/codersgate/ticketraider/domain/category/model/Category.kt
src/main/kotlin/com/codersgate/ticketraider/domain/category/repository/CategoryRepository.kt
src/main/kotlin/com/codersgate/ticketraider/domain/category/repository/CategoryRepositoryImpl.kt
src/main/kotlin/com/codersgate/ticketraider/domain/category/repository/CustomCategoryRepository.kt
src/main/kotlin/com/codersgate/ticketraider/domain/category/service/CategoryService.kt
src/main/kotlin/com/codersgate/ticketraider/domain/category/service/CategoryServiceImpl.kt
src/main/kotlin/com/codersgate/ticketraider/domain/ticket/controller/TicketController.kt
src/main/kotlin/com/codersgate/ticketraider/error/exception/AccessDeniedException.kt
src/main/kotlin/com/codersgate/ticketraider/error/exception/EmailAlreadyExistException.kt
src/main/kotlin/com/codersgate/ticketraider/error/exception/GlobalExceptionHandler.kt
src/main/kotlin/com/codersgate/ticketraider/error/exception/ModelNotFoundException.kt
src/main/kotlin/com/codersgate/ticketraider/error/exception/dto/BaseResponse.kt
src/main/kotlin/com/codersgate/ticketraider/error/exception/dto/ErrorResponse.kt
src/main/kotlin/com/codersgate/ticketraider/error/exception/status/ResultCode.kt
src/main/kotlin/com/codersgate/ticketraider/infra/querydsl/QueryDslSupport.kt

다른 팀원분들 Exception 이나 Base Entity 받아가셔서 쓰시길 바랍니다.

#2 Feat : Category, Infra, Exception, Common 패키지 생성 및 구현

---

src/main/kotlin/com/codersgate/ticketraider/domain/category/model/Category.kt
src/main/kotlin/com/codersgate/ticketraider/domain/category/repository/CategoryRepositoryImpl.kt
src/main/kotlin/com/codersgate/ticketraider/domain/category/service/CategoryServiceImpl.kt
src/main/kotlin/com/codersgate/ticketraider/error/exception/dto/ErrorResponse.kt
src/main/kotlin/com/codersgate/ticketraider/global/common/BaseEntity.kt
src/main/kotlin/com/codersgate/ticketraider/global/error/exception/AccessDeniedException.kt
src/main/kotlin/com/codersgate/ticketraider/global/error/exception/EmailAlreadyExistException.kt
src/main/kotlin/com/codersgate/ticketraider/global/error/exception/GlobalExceptionHandler.kt
src/main/kotlin/com/codersgate/ticketraider/global/error/exception/ModelNotFoundException.kt
src/main/kotlin/com/codersgate/ticketraider/global/error/exception/dto/BaseResponse.kt
src/main/kotlin/com/codersgate/ticketraider/global/error/exception/dto/ErrorResponse.kt
src/main/kotlin/com/codersgate/ticketraider/global/error/exception/status/ResultCode.kt
src/main/kotlin/com/codersgate/ticketraider/global/infra/querydsl/QueryDslSupport.kt
src/main/kotlin/com/codersgate/ticketraider/global/infra/swagger/SwaggerConfig.kt

#2 Feat : SwaggerConfig 생성

---

src/main/kotlin/com/codersgate/ticketraider/domain/review/controller/ReviewController.kt
src/main/kotlin/com/codersgate/ticketraider/domain/review/dto/CreateReviewRequest.kt
src/main/kotlin/com/codersgate/ticketraider/domain/review/dto/ReviewResponse.kt
src/main/kotlin/com/codersgate/ticketraider/domain/review/dto/UpdateReviewRequest.kt
src/main/kotlin/com/codersgate/ticketraider/domain/review/model/Review.kt
src/main/kotlin/com/codersgate/ticketraider/domain/review/repository/CustomReviewRepository.kt
src/main/kotlin/com/codersgate/ticketraider/domain/review/repository/CustomReviewRepositoryImpl.kt
src/main/kotlin/com/codersgate/ticketraider/domain/review/repository/ReviewRepository.kt
src/main/kotlin/com/codersgate/ticketraider/domain/review/service/ReviewService.kt
src/main/kotlin/com/codersgate/ticketraider/domain/review/service/ReviewServiceImpl.kt

Review Entity 관련 CRUD 완성입니다.
User 와 Event 가 완성되면 Id 받는 부분만 주석 해제하면 될 것 같습니다.
여러 건 조회엔 페이징 적용 하였습니다.
fun createReview(request: CreateReviewRequest)
fun getReviewList(pageable : Pageable) : Page<ReviewResponse>
// 통합 조회
fun getReviewList_V2(pageable: Pageable,userId : Long,eventId : Long) : Page<ReviewResponse>
fun getReviewListByEvent(pageable : Pageable, eventId : Long) : Page<ReviewResponse>
fun getReviewListByUser(pageable : Pageable, userId: Long) : Page<ReviewResponse>
fun getReview(reviewId : Long) : ReviewResponse
fun updateReview(reviewId: Long, request : UpdateReviewRequest)
fun deleteReview(reviewId: Long)
close #4

Feature/review Review CRUD 완성

---

src/main/kotlin/com/codersgate/ticketraider/domain/member/controller/MemberController.kt
src/main/kotlin/com/codersgate/ticketraider/domain/member/entity/Member.kt
src/main/kotlin/com/codersgate/ticketraider/domain/member/service/MemberService.kt
src/main/kotlin/com/codersgate/ticketraider/domain/member/service/MemberServiceImpl.kt

Fix: Enumerated 타입 오류 수정

---

src/main/kotlin/com/codersgate/ticketraider/domain/member/entity/MemberRole.kt
src/main/kotlin/com/codersgate/ticketraider/domain/member/service/MemberServiceImpl.kt

Fix: MemberRole enum User->Member로 변경

---

src/main/kotlin/com/codersgate/ticketraider/domain/event/service/EventServiceImpl.kt
src/main/kotlin/com/codersgate/ticketraider/domain/like/controller/LikeController.kt
src/main/kotlin/com/codersgate/ticketraider/domain/like/dto/LikeResponse.kt
src/main/kotlin/com/codersgate/ticketraider/domain/like/model/Like.kt
src/main/kotlin/com/codersgate/ticketraider/domain/like/repository/CustomLikeRepository.kt
src/main/kotlin/com/codersgate/ticketraider/domain/like/repository/CustomLikeRepositoryImpl.kt
src/main/kotlin/com/codersgate/ticketraider/domain/like/repository/LikeRepository.kt
src/main/kotlin/com/codersgate/ticketraider/domain/like/service/LikeService.kt
src/main/kotlin/com/codersgate/ticketraider/domain/like/service/LikeServiceImpl.kt
src/main/kotlin/com/codersgate/ticketraider/domain/member/controller/MemberController.kt
src/main/kotlin/com/codersgate/ticketraider/domain/review/controller/ReviewController.kt
src/main/kotlin/com/codersgate/ticketraider/domain/review/service/ReviewService.kt
src/main/kotlin/com/codersgate/ticketraider/domain/review/service/ReviewServiceImpl.kt

getLikeList ( 좋아요 기록 조회 . memberId 별, eventId 별 )
getLike( 좋아요 단건 조회 )
createLike ( 좋아요 기록 확인 후 상태값 변경 )
deleteLike ( softDelete )

#14 Feature/like 구현 완료 ( 테스트 필요 )

---

src/main/kotlin/com/codersgate/ticketraider/domain/ticket/controller/TicketController.kt
src/main/kotlin/com/codersgate/ticketraider/domain/ticket/dto/CreateTicketRequest.kt
src/main/kotlin/com/codersgate/ticketraider/domain/ticket/dto/TicketResponse.kt
src/main/kotlin/com/codersgate/ticketraider/domain/ticket/entity/Ticket.kt
src/main/kotlin/com/codersgate/ticketraider/domain/ticket/entity/TicketGrade.kt
src/main/kotlin/com/codersgate/ticketraider/domain/ticket/repository/CustomTicketRepository.kt
src/main/kotlin/com/codersgate/ticketraider/domain/ticket/repository/TicketRepository.kt
src/main/kotlin/com/codersgate/ticketraider/domain/ticket/repository/TicketRepositoryImpl.kt
src/main/kotlin/com/codersgate/ticketraider/domain/ticket/service/TicketService.kt
src/main/kotlin/com/codersgate/ticketraider/domain/ticket/service/TicketServiceImpl.kt

#31
- CRUD
- 생성, 삭제, 단건 조회, 리스트 조회
- 티켓 수정은 정책 논의 필요

Feat: Ticket Package 추가

---

src/main/kotlin/com/codersgate/ticketraider/global/infra/security/SecurityConfig.kt
src/main/resources/application.yml

SecurityConfig 의 return http 설정 중 .headers { it.frameOptions{ option -> option.sameOrigin() } } // H2 설정 추가,
yml 설정 추가

#29 Fix/set h2

---

src/main/kotlin/com/codersgate/ticketraider/domain/member/controller/MemberController.kt
src/main/kotlin/com/codersgate/ticketraider/domain/member/entity/Member.kt

#33 
- likes, reviews 연관관계 @OnetoMany로 추가
- MemberController의 updateProfile에 @Valid 어노테이션 추가

Fix: Member Package 연관관계 수정, @valid 어노테이션 빠진 거 수정

---

src/main/kotlin/com/codersgate/ticketraider/domain/event/controller/EventController.kt
src/main/kotlin/com/codersgate/ticketraider/domain/event/dto/CreateEventRequest.kt
src/main/kotlin/com/codersgate/ticketraider/domain/event/dto/EventResponse.kt
src/main/kotlin/com/codersgate/ticketraider/domain/event/dto/UpdateEventRequest.kt
src/main/kotlin/com/codersgate/ticketraider/domain/event/dto/price/CreatePriceRequest.kt
src/main/kotlin/com/codersgate/ticketraider/domain/event/dto/price/PriceResponse.kt
src/main/kotlin/com/codersgate/ticketraider/domain/event/dto/price/UpdatePriceRequest.kt
src/main/kotlin/com/codersgate/ticketraider/domain/event/dto/seat/CreateSeatRequest.kt
src/main/kotlin/com/codersgate/ticketraider/domain/event/dto/seat/SeatResponse.kt
src/main/kotlin/com/codersgate/ticketraider/domain/event/dto/seat/UpdateSeatRequest.kt
src/main/kotlin/com/codersgate/ticketraider/domain/event/model/Event.kt
src/main/kotlin/com/codersgate/ticketraider/domain/event/model/price/Price.kt
src/main/kotlin/com/codersgate/ticketraider/domain/event/model/seat/Bookable.kt
src/main/kotlin/com/codersgate/ticketraider/domain/event/model/seat/Seat.kt
src/main/kotlin/com/codersgate/ticketraider/domain/event/repository/EventRepository.kt
src/main/kotlin/com/codersgate/ticketraider/domain/event/repository/price/PriceRepository.kt
src/main/kotlin/com/codersgate/ticketraider/domain/event/repository/seat/SeatRepository.kt
src/main/kotlin/com/codersgate/ticketraider/domain/event/service/EventService.kt
src/main/kotlin/com/codersgate/ticketraider/domain/event/service/EventServiceImpl.kt
src/main/kotlin/com/codersgate/ticketraider/domain/place/repository/PlaceRepository.kt

#13 ServiceImpl 구현 전에 create 부분만 풀리퀘 후 작동확인

Feature/event price&seat

---

src/main/kotlin/com/codersgate/ticketraider/domain/like/controller/LikeController.kt
src/main/kotlin/com/codersgate/ticketraider/domain/like/repository/CustomLikeRepository.kt
src/main/kotlin/com/codersgate/ticketraider/domain/like/repository/CustomLikeRepositoryImpl.kt
src/main/kotlin/com/codersgate/ticketraider/domain/like/repository/LikeRepository.kt
src/main/kotlin/com/codersgate/ticketraider/domain/like/service/LikeService.kt
src/main/kotlin/com/codersgate/ticketraider/domain/like/service/LikeServiceImpl.kt
src/main/kotlin/com/codersgate/ticketraider/domain/member/entity/Member.kt

- Like 생성, 조회 테스트 성공
- createLike 를 chkLike 로 수정, Create 와 Delete 역할 통합
- chkLike 실행 시 Event.likeCount 변경되도록 확인.
- 전체 likeCount 갯수 최신화 메서드 구현 완료

#14 Feature/like count 기능 구현 / 테스트 완료

---

src/main/kotlin/com/codersgate/ticketraider/domain/member/entity/Member.kt
src/main/kotlin/com/codersgate/ticketraider/domain/member/service/MemberServiceImpl.kt

- MemberServiceImpl의 updateProfile에서 password 암호화 추가
- Member 엔티티의 updateProfile 파라미터 변경

Fix: updateProfile 호출 시 password 암호화 되지 않는 문제 수정

---

src/main/kotlin/com/codersgate/ticketraider/domain/ticket/dto/TicketResponse.kt
src/main/kotlin/com/codersgate/ticketraider/domain/ticket/entity/Ticket.kt
src/main/kotlin/com/codersgate/ticketraider/domain/ticket/entity/TicketStatus.kt
src/main/kotlin/com/codersgate/ticketraider/domain/ticket/service/TicketServiceImpl.kt

-  TicketEntity에 ticketStatus, price, place 추가
- TicketResponse 변경
- ServiceImpl에서 createTicket 수정

Refactor: Ticket Entity, dto 수정, TicketStatus 추가

---

src/main/kotlin/com/codersgate/ticketraider/domain/event/repository/CustomEventRepository.kt
src/main/kotlin/com/codersgate/ticketraider/domain/event/repository/EventRepositoryImpl.kt
src/main/kotlin/com/codersgate/ticketraider/domain/event/service/EventServiceImpl.kt
src/main/kotlin/com/codersgate/ticketraider/domain/ticket/service/TicketServiceImpl.kt
src/main/kotlin/com/codersgate/ticketraider/global/infra/redis/RedisConfig.kt

- 캐시에서 키 불러올 때 캐시명은 생략하고 검색해야함. ( 'ticket::' 부분)
- Redis-cli 에서 GET 으로 검색할 땐 캐시명도 붙여야함.

Feature/redis cache serialize Feature : 캐시 키 검색 오류 수정

---

src/main/kotlin/com/codersgate/ticketraider/domain/category/repository/CategoryRepository.kt
src/main/kotlin/com/codersgate/ticketraider/domain/category/service/CategoryServiceImpl.kt
src/main/kotlin/com/codersgate/ticketraider/domain/event/controller/EventController.kt
src/main/kotlin/com/codersgate/ticketraider/domain/event/dto/EventRequest.kt
src/main/kotlin/com/codersgate/ticketraider/domain/event/repository/EventRepository.kt
src/main/kotlin/com/codersgate/ticketraider/domain/event/service/EventServiceImpl.kt
src/main/kotlin/com/codersgate/ticketraider/domain/place/service/PlaceServiceImpl.kt
src/main/kotlin/com/codersgate/ticketraider/domain/ticket/entity/Ticket.kt
src/main/kotlin/com/codersgate/ticketraider/domain/ticket/repository/TicketRepository.kt

Event, Category 에 알맞은 내용이 들어가는지 확인하는 코드 작성
Event 생성시에 endDate가 startDate 보다 앞에 있으면 생성 불가능
Seat 생성시에 기존에 이미 있는 날짜는 생성 불가능
Category 생성시 기존에 이미 있는 title이면 생성 불가능

#62 Feat : Event, Category CRUD 수정

---

src/main/kotlin/com/codersgate/ticketraider/domain/event/dto/EventRequest.kt
src/main/kotlin/com/codersgate/ticketraider/domain/event/repository/seat/AvailableSeatRepository.kt
src/main/kotlin/com/codersgate/ticketraider/domain/event/service/EventServiceImpl.kt
src/main/kotlin/com/codersgate/ticketraider/domain/place/controller/PlaceController.kt
src/main/kotlin/com/codersgate/ticketraider/domain/place/dto/CreatePlaceRequest.kt
src/main/kotlin/com/codersgate/ticketraider/domain/place/dto/PlaceRequest.kt
src/main/kotlin/com/codersgate/ticketraider/domain/place/dto/UpdatePlaceResponse.kt
src/main/kotlin/com/codersgate/ticketraider/domain/place/service/PlaceService.kt
src/main/kotlin/com/codersgate/ticketraider/domain/place/service/PlaceServiceImpl.kt
src/main/kotlin/com/codersgate/ticketraider/domain/ticket/repository/CustomTicketRepository.kt
src/main/kotlin/com/codersgate/ticketraider/domain/ticket/repository/TicketRepositoryImpl.kt

EventUpdate 시 date 기반으로 기존에 있는 seat 는 그대로 두고 없을시 새로 생성
PlaceServcieImpl 코드 간결화

#62 Fix/event

---

src/main/kotlin/com/codersgate/ticketraider/domain/event/controller/EventController.kt
src/main/kotlin/com/codersgate/ticketraider/domain/event/dto/EventResponse.kt
src/main/kotlin/com/codersgate/ticketraider/domain/event/model/Event.kt
src/main/kotlin/com/codersgate/ticketraider/domain/event/repository/CustomEventRepository.kt
src/main/kotlin/com/codersgate/ticketraider/domain/event/repository/EventRepositoryImpl.kt

#62
likecount , reviewcount 기준으로 조회 기능 추가

#feat : likecount , reviewcount 기준으로 조회 기능 추가

---

src/main/kotlin/com/codersgate/ticketraider/domain/place/controller/PlaceController.kt
src/main/kotlin/com/codersgate/ticketraider/domain/place/repository/PlaceRepository.kt
src/main/kotlin/com/codersgate/ticketraider/domain/place/service/PlaceService.kt
src/main/kotlin/com/codersgate/ticketraider/domain/place/service/PlaceServiceImpl.kt
src/main/kotlin/com/codersgate/ticketraider/domain/review/controller/ReviewController.kt
src/main/kotlin/com/codersgate/ticketraider/domain/review/service/ReviewServiceImpl.kt
src/main/kotlin/com/codersgate/ticketraider/domain/ticket/controller/TicketController.kt
src/main/kotlin/com/codersgate/ticketraider/domain/ticket/repository/CustomTicketRepository.kt
src/main/kotlin/com/codersgate/ticketraider/domain/ticket/repository/TicketRepository.kt
src/main/kotlin/com/codersgate/ticketraider/domain/ticket/repository/TicketRepositoryImpl.kt
src/main/kotlin/com/codersgate/ticketraider/domain/ticket/service/TicketService.kt
src/main/kotlin/com/codersgate/ticketraider/domain/ticket/service/TicketServiceImpl.kt

placeId 입력받아 해당 장소의 이벤트 리스트 불러오기

Place 별 이벤트 리스트 조회 추가 #62

---

src/main/kotlin/com/codersgate/ticketraider/domain/event/model/seat/AvailableSeats.kt
src/main/kotlin/com/codersgate/ticketraider/domain/review/service/ReviewServiceImpl.kt
src/main/kotlin/com/codersgate/ticketraider/domain/ticket/controller/TicketController.kt
src/main/kotlin/com/codersgate/ticketraider/domain/ticket/service/TicketService.kt
src/main/kotlin/com/codersgate/ticketraider/domain/ticket/service/TicketServiceImpl.kt

LOCK 와 중복 기능 수행하여 캐싱 과정 제거
각종 유효 처리 과정 리팩토링

#60 Feature/ticket 티켓 생성 과정 리팩토링

---

src/main/kotlin/com/codersgate/ticketraider/domain/member/controller/MemberController.kt
src/main/kotlin/com/codersgate/ticketraider/domain/member/entity/Member.kt
src/main/kotlin/com/codersgate/ticketraider/domain/member/entity/ProviderMap.kt
src/main/kotlin/com/codersgate/ticketraider/domain/member/repository/MemberRepository.kt
src/main/kotlin/com/codersgate/ticketraider/domain/member/repository/ProviderMapRepository.kt
src/main/kotlin/com/codersgate/ticketraider/domain/member/service/MemberService.kt
src/main/kotlin/com/codersgate/ticketraider/domain/member/service/MemberServiceImpl.kt
src/main/kotlin/com/codersgate/ticketraider/global/infra/security/SecurityConfig.kt

Reverts LSW990918/TicketRaider#80

Revert "Feature/member rejoin"

---

src/main/kotlin/com/codersgate/ticketraider/domain/member/controller/MemberController.kt

closes #92
- Member 패키지 updateProfile, register 메소드 수정

Fix: Member 패키지 authentication 객체 얻는 방식 수정
